### ISSUE TITLE
Upgrade Pydantic to v2

### ISSUE THREAD

**Issue by jake-skipper** [onicagroup/runway#2101]
Runway uses Pydantic extensively, and awhile back they moved to v2. We haven't received those updates due to package pinning and some changes will be required to move to v2.

**Comment by ITProKyle** [comment]
The decision was made to perform this upgrade, even though it is breaking, in a minor release rather than major.

Tasks to be completed:

- [ ] EoL of binary releases (pyinstaller) to S3 and npm
  - [ ] remove jobs that build, publish, etc these
- [ ] remove code and dependencies specific to pyinstaller 
- [ ] mark npm package as deprecated with message
- [ ] update install docs & README
- [ ] update pyright to the latest version now that it can be updated
