### ISSUE TITLE
Static site Auth@Edge reports a red "ERROR" during lambda builds

### ISSUE THREAD

**Issue by troyready** [onicagroup/runway#345]
Deploying an auth@edge-enabled static site (at least on my system -- Runway 1.8 in pipenv on Ubuntu 20.04) generates the following output (among a bunch of other lines):

```
INFO:runway.cfngin.hooks.aws_lambda:lambda: using custom bucket: mynamespace-frontend-dependencie-artifacts-18wze3vbi33ga
INFO:runway.cfngin.hooks.aws_lambda:lambda: using requirements.txt for dependencies
Collecting ecdsa==0.15
  Using cached ecdsa-0.15-py2.py3-none-any.whl (100 kB)
Collecting pyasn1==0.4.8
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting pyjwt==1.7.1
  Using cached PyJWT-1.7.1-py2.py3-none-any.whl (18 kB)
Collecting python-jose==3.1.0
  Using cached python_jose-3.1.0-py2.py3-none-any.whl (26 kB)
Collecting rsa==4.0
  Using cached rsa-4.0-py2.py3-none-any.whl (38 kB)
Collecting six==1.14.0
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
ERROR: runway 1.8.0 requires zipp~=1.0.0, which is not installed.
ERROR: awscli 1.18.62 has requirement rsa<=3.5.0,>=3.1.2, but you'll have rsa 4.0 which is incompatible.
Installing collected packages: six, ecdsa, pyasn1, pyjwt, rsa, python-jose
Successfully installed ecdsa-0.15 pyasn1-0.4.8 pyjwt-1.7.1 python-jose-3.1.0 rsa-4.0 six-1.14.0
INFO:runway.cfngin.hooks.aws_lambda:lambda: object lambda-check_auth-be24ce1bd52bfe0b7131c22df54e9778.zip already exists, not uploading
```

The 2 ERROR lines from pip are colored red. The RSA conflict [is due to an awscli issue](https://github.com/aws/aws-cli/issues/3660); I'm not sure what's causing the zipp issue but I don't think it's important.

**Comment by troyready** [comment]
The most simple way to fix this is to add `--no-warn-conflicts` to [the list of pip options here](https://github.com/onicagroup/runway/blob/v1.8.0/runway/cfngin/hooks/aws_lambda.py#L525-L526) -- for me that changed the output to:

...
INFO:runway.cfngin.hooks.aws_lambda:lambda: using custom bucket: mynamespace-frontend-dependencie-artifacts-18wze3vbi33ga
INFO:runway.cfngin.hooks.aws_lambda:lambda: using requirements.txt for dependencies
Collecting ecdsa==0.15
  Using cached ecdsa-0.15-py2.py3-none-any.whl (100 kB)
Collecting pyasn1==0.4.8
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting pyjwt==1.7.1
  Using cached PyJWT-1.7.1-py2.py3-none-any.whl (18 kB)
Collecting python-jose==3.1.0
  Using cached python_jose-3.1.0-py2.py3-none-any.whl (26 kB)
Collecting rsa==4.0
  Using cached rsa-4.0-py2.py3-none-any.whl (38 kB)
Collecting six==1.14.0
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: six, ecdsa, pyasn1, pyjwt, rsa, python-jose
Successfully installed ecdsa-0.15 pyasn1-0.4.8 pyjwt-1.7.1 python-jose-3.1.0 rsa-4.0 six-1.14.0
INFO:runway.cfngin.hooks.aws_lambda:lambda: object lambda-check_auth-be24ce1bd52bfe0b7131c22df54e9778.zip already exists, not uploading
...
(notably no ERROR/red lines).

I _think_ that's fine to do -- makes me a little worried that I'm suggesting taking away useful debug info, but I'm also hesitant to add another option to the hook.

Would appreciate your thoughts @ITProKyle

**Comment by ITProKyle** [comment]
This is a shortcoming of how pip handles dependencies. It does not exclude global installs from incompatibility checks when installing to a target directory. There is an issue currently open in the pip repo for this but it has not had any movement (pypa/pip#7821).

> makes me a little worried that I'm suggesting taking away useful debug info

I am not a fan of hiding the output with a flag either. It could prevent important information from being displayed when using the hook outside of a@e. The errors being raised right now are only cosmetic. Install still occurs but this may not be the case forever.

I would rather address the root cause than _patching_ it by hiding the output. The pip dependency resolver is in the process of being refactored (pypa/pip#988) so a case could be made for fixing this at the source.

**Comment by ITProKyle** [comment]
internal discussion lead to the decision to disable colorized output for pip to remove the red lines instead of ignoring them. a message will also be logged explaining the potential existence of these errors. The screenshot below is an example of the new output.

![image](https://user-images.githubusercontent.com/23145462/83165735-d1ab8580-a0c2-11ea-8e4c-934477ed1dce.png)

@troyready - how detailed should the message about the errors be? The one in the screenshot provides the relative information but could be a bit long for a log statement. would shortening it to something like _"Some incompatibility errors reported by pip can be ignored."_ be sufficient?
