### ISSUE TITLE
[BUG] creating a static website in a region outside of us-east-1 doesn't work.

### ISSUE THREAD

**Issue by burib** [onicagroup/runway#445]
**Describe the bug**
Creating a static website in a region outside of us-east-1 doesn't work.

**To Reproduce**
1. git clone https://github.com/burib/runway-static-website-bug
2. npm install
3. npm run deploy
4. check both cloudfront distributions
5. wonder why is us-east-1 but the rest doesn't work. ( my hunch is that it's related to OAI creation )

**Expected behavior**
Static website creation with cloudfront enabled works in all regions.

**Desktop (please complete the following information):**
 - OS: osx
 - Version 10.15.6

**Additional context**
code to reproduce the bug is here: https://github.com/burib/runway-static-website-bug

**Comment by ITProKyle** [comment]
I was able to reproduce the issue. For distributions created in regions other than us-east-1, the following is returned when trying to access the distribution's domain name.

```xml
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>B8ED072A7959BB87</RequestId>
  <HostId>string</HostId>
</Error>
```

The URL was redirected to `https://<bucket-name>.s3-<region>.amazonaws.com/index.html`.

Still researching the issue.

**Comment by ITProKyle** [comment]
This looks the be cause cause of the issue: https://github.com/onicagroup/runway/blob/v1.12.0/runway/blueprints/staticsite/staticsite.py#L375-L377

[![image](https://user-images.githubusercontent.com/23145462/93118014-781c9600-f674-11ea-8477-72b3331ef68d.png)](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html)

Removing the `WebsiteConfiguration` allowed me to correctly access the website through both distributions.

Given the messaging in the AWS docs, I'm surprised this worked in us-east-1 but then again this is far from the first functionality misalignment between us-east-1 and all other regions.

**Comment by burib** [comment]
thanks for the quick check @ITProKyle 

however after upgrading to 1.13.0 I can still [reproduce](https://github.com/burib/runway-static-website-bug) it.

**Comment by ITProKyle** [comment]
@burib - I can reproduce it as well which is odd.

Yesterday, I was able to toggle it between working and not working with the inclusion/removal of `WebsiteConfiguration`.

When you tested it, were you using brand new buckets/distributions? When I deployed it this morning I used new resources (destroyed the others yesterday after testing).

Looking into this a bit more, I ran across [this on the AWS forums](https://forums.aws.amazon.com/message.jspa?messageID=677452) which seems to describe the behavior we are seeing.

When a new bucket is created, it is immediately accessible from the regional endpoint. By default (and how we have it setup in CFN) CloudFront uses the the global endpoint for the S3 bucket. For new buckets, it can take up to and some times over an hour for the global endpoint to become accessible. During this time, CloudFront uses a temporary redirect to the regional endpoint which results in it redirecting straight to the S3 object which will show access denied for a private bucket. This behavior is more transparent when curling the CloudFront domain name.

```shell
$ curl -I https://dlja1v5596z2v.cloudfront.net/index.html
HTTP/1.1 307 Temporary Redirect
Content-Type: application/xml
Connection: keep-alive
x-amz-bucket-region: us-west-2
Location: https://finley-lab-bugtest-us-west-2-ui-bucket-1nfo5ix0b7pwh.s3-us-west-2.amazonaws.com/index.html
Date: Tue, 15 Sep 2020 15:34:59 GMT
Server: AmazonS3
X-Cache: Miss from cloudfront
Via: 1.1 89a4ab78825672db6312480622f560a1.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: LAX3-C3
X-Amz-Cf-Id: f-dXLQxPrcUl3ljQixqafcAPm87PSsRYy3iZaVuogb8ASRZiOVfgOw==
```

The reason why this always works instantly is because us-east-1 uses the global endpoint as its regional endpoint making it update instantly.

According to the linked forums post, after an update in ~2018 CloudFront now accepts manual entry of a regional endpoint (even though the console only provides global endpoints) to avoid the temporary redirect we are seeing. I am verifying this now.

**Comment by burib** [comment]
I've destroyed everything and started from scratch, that's how I reproduced it.

I can check later if I can set this up manually through the console using eu-west-1

**Comment by ITProKyle** [comment]
Just did a fresh deployment to eu-west-1 using the regional endpoint as the CloudFront origin and it worked instantly - [d1b3icy7kuvmz4.cloudfront.net](https://d1b3icy7kuvmz4.cloudfront.net) (will be destroying in ~15 minutes, after I get the PR prepped).

![image](https://user-images.githubusercontent.com/23145462/93241183-da8b9a00-f739-11ea-85ad-8df15c05d40c.png)
