### ISSUE TITLE
runway updating existing stack when there are no changes

### ISSUE THREAD

**Issue by newbeeeeeee** [onicagroup/runway#499]
We are currently using runway (version 1.4.4) in CICD pipelines and are running into a strange issue. Our runway plan does not find any change but during runway deploy stage we see most of the stacks getting updated. In cloudtrail logs we are able to see:

```
    "userAgent": "Boto3/1.16.35 Python/3.7.6 Linux/4.14.203-116.332.amzn1.x86_64 exec-env/AWS_ECS_EC2 Botocore/1.19.35",
    "errorCode": "ValidationException",
    "errorMessage": "No updates are to be performed.",
    "requestParameters": null,
    "responseElements": null,
```

It appears no resources are updated. Has anyone seen this issue before?

**Comment by troyready** [comment]
The only times I've seen this come up is due to CFN stack tags changing, which don't show up on the Runway plan output. I'm not 100% certain where the fault of the bug is; my guess is that we're not getting enough data back from the CFN change set to detect the change, but it's possible Runway is doing something incorrect.

Going to leave this issue open for someone to test and verify this -- easy way to trigger it should be to deploy a stack with an old (say v1.1) version of Runway and then update to the latest version.

**Comment by newbeeeeeee** [comment]
Thanks @troyready . We have run into the tag issue before and we see it with different runway versions. We are still investigating.....

**Comment by ITProKyle** [comment]
I have also seen Stacker (pre CFNgin) show no change in a change set during plan but still submit a stack for update when using parameters with `NoEcho`. Do any of the templates you are seeing this happen with have any parameters that use `NoEcho` or are of a type other than `String`, `Number`, or `CommaDelimitedList`?

I would also suggest updating to the current version of Runway as there have been quite a few changes/patches since 1.4.4.

**Comment by ITProKyle** [comment]
Closing as this relates to quite an old version of runway at this point and there have been no reports from other users. If it can be reproduced with a current version of runway and a reproducible situation can be provided, a new issue can be opened.
