### ISSUE TITLE
[REQUEST] Use AWSServiceRoleForAmazonEKS instead of custom role

### ISSUE THREAD

**Issue by jeffkloy** [onicagroup/runway#502]
https://github.com/onicagroup/runway/blob/4424a70f0ded48e8b2b9df715c84516c3d5cd3e8/runway/templates/k8s-tf-repo/eks-base.tf/main.tf#L72

Just a suggestion, AWS mentions "Prior to April 16, 2020, AmazonEKSServicePolicy was also required and the suggested name was eksServiceRole. With the AWSServiceRoleForAmazonEKS service-linked role, that policy is no longer required for clusters created on or after April 16, 2020" on https://docs.aws.amazon.com/eks/latest/userguide/service_IAM_role.html

Perhaps we can re-write to use this role (AWSServiceRoleForAmazonEKS), instead of making our own custom role.

**Comment by troyready** [comment]
Thanks for the tip @jeffkloy 

> Perhaps we can re-write to use this role (AWSServiceRoleForAmazonEKS), instead of making our own custom role.

fwiw, a custom role is still required -- if you call CreateCluster with the roleArn set to the AWS managed service-linked role, you get a `The provided role doesn't have the Amazon EKS Managed Policies associated with it. Please ensure the following policies [arn:aws:iam::aws:policy/AmazonEKSClusterPolicy] are attached` error. But since the service-linked role has the `AmazonEKSServiceRolePolicy` managed policy on it, that policy is no longer needed on the cluster role
