### ISSUE TITLE
[Request] Add support for S3 default encryption on runway's S3 bucket

### ISSUE THREAD

**Issue by dailyherold** [onicagroup/runway#54]
We run in an environment where all buckets require default encryption. Any plans on supporting AES and KMS key support for runway's S3 bucket? I'm not yet familiar with code base but can start taking a look as time permits.

**Comment by ITProKyle** [comment]
The bucket that is automatically deployed i, by design, _bare minimum_ needed for caching CloudFormation templates to meet the majority of use cases. There are currently no plans to add additional configuration for this bucket since a custom bucket can be deployed to meet any additional.

To deploy a custom bucket:

1. Create a template or blueprint for your desired bucket. The bucket should have a predictable name. Personally, I use something like `<namespace>-cfngin-<region>`.
2. Configure a module to deploy it before anything else. This can be done as a dedicated module or part of an existing one since Runway supports the use of multiple CFNgin config files in a directory but, the config file would need to be named in such a way that it comes first in alphanumerical order.
3. In the config file deploying the bucket, it should have the the CFNgin bucket configured as an empty string to prevent one from being created (e.g. `cfngin_bucket: ''`).
4. To use the custom bucket that was deployed in other CFNgin config files, provide the predictable bucket name (e.g. `cfngin_bucket: ${namespace}-cfngin-${region}`).
