### ISSUE TITLE
kbenv interactions with awscliv2 need an integration test

### ISSUE THREAD

**Issue by troyready** [onicagroup/runway#550]
#548 was resolved with a quick hotfix, but nothing is preventing the same issue from returning in the future.

**Comment by ITProKyle** [comment]
This could be difficult to test for/prevent. The biggest issue is that `awscli >= 2` & `botocore >= 2` are not published to PyPi and won't be for the forceable future (https://github.com/aws/aws-cli/issues/4947) so we can't rely on using v2.

v2 is also not even installed as a python package - it's bundled with pyinstaller like we do for Runway on npm so I'm not sure why it or any of its component's are being used since it _should_ be siloed.

**Comment by troyready** [comment]
I tend to agree. Fine with pushing this off pending a better v2 install story (their plans for a 'source archive' or however they phrased it sounds reasonable enough to deal with).

fwiw (in case it ends up being relevant here or to something related) here's how I'm using v2 now on linux:
```
pipx install awscli
~/.local/pipx/venvs/awscli/bin/python -m pip install https://github.com/boto/botocore/archive/v2.zip  https://github.com/aws/aws-cli/archive/v2.zip
TMP_CLI_INDEXGEN=$(mktemp -d)
curl -Lo $TMP_CLI_INDEXGEN/gen-ac-index https://github.com/aws/aws-cli/raw/v2/scripts/gen-ac-index && ~/.local/pipx/venvs/awscli/bin/python3 $TMP_CLI_INDEXGEN/gen-ac-index --include-builtin-index
```

**Comment by ITProKyle** [comment]
We may be better off removing awscli as a dependency to avoid the error all together - it would also greatly simplify Runway's dependencies. IIRC Runway itself (not factoring in samples) only uses awscli in the hooks that are a part of static site deployments to sync files with an S3 Bucket. We should be able to reproduce the functionality without using awscli.

**Comment by troyready** [comment]
> We may be better off removing awscli as a dependency to avoid the error/conflict all together

I wouldn't necessarily be opposed to it. It's incidentally nice for a featureset I doubt a single person ever used (e.g. using `runway run-aws` for eks auth). No reason advanced usage can't be moved to pipenv/poetry.
